apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-syslog-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: k8s-syslog-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-syslog-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-syslog-reader
subjects:
- kind: ServiceAccount
  name: k8s-syslog-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-syslog
  namespace: default
  labels:
    app: k8s-syslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-syslog
  template:
    metadata:
      labels:
        app: k8s-syslog
    spec:
      serviceAccountName: k8s-syslog-sa
      containers:
        - image: docker.io/84codes/k8s-syslog
          name: k8s-syslog
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
              ephemeral-storage: 1Mi
            requests:
              cpu: 100m
              memory: 64Mi
              ephemeral-storage: 1Mi
          envFrom:
            - secretRef:
                name: k8s-syslog
