name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  format:
    runs-on: ubuntu-latest
    continue-on-error: true
    container: 84codes/crystal
    steps:
      - uses: actions/checkout@v3
      - run: crystal tool format --check

  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    container: 84codes/crystal
    steps:
      - uses: actions/checkout@v3
      - run: shards install
      - run: bin/ameba --no-color

  spec:
    runs-on: ubuntu-latest
    container: 84codes/crystal
    steps:
      - uses: actions/checkout@v3
      - run: crystal spec --no-color --order random

  container:
    runs-on: ubuntu-latest
    needs: [format, lint, spec]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        with:
          images: 84codes/k8s-syslog
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
        id: meta
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.event_name != 'pull_request'
      - uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
